#!/usr/bin/env bash

set -euo pipefail

VERSION=1.0.0
INSTALL_PATH=/var/lib
AV_PATH=$INSTALL_PATH/aviary/av
RELEASE_URL=https://gitlab.com/dchester/aviary.sh/-/archive/${VERSION}/aviary.sh-${VERSION}.tar.gz
INVENTORY_GIT_URL=${1:-""}

# check for git dependency
if ! /usr/bin/which git; then
  echo "Please install git and try again"
  exit 1
fi

if [[ -z "$INVENTORY_GIT_URL" ]]; then
  echo "Installing with no inventory git url; set later in $INSTALL_PATH/aviary/config"
fi

if [[ -e /var/lib/aviary ]]; then 
  echo "Found existing installation at $INSTALL_PATH"
  exit 1
fi

echo Installing to ${INSTALL_PATH}...
mkdir -p ${INSTALL_PATH}/aviary
curl $RELEASE_URL | tar --strip-components=1 -C ${INSTALL_PATH}/aviary -xz
ln -s /var/lib/aviary/av /usr/bin/av

echo Adding entry to /etc/crontab...
echo "$(cat /etc/crontab | grep -v $AV_PATH)" > /etc/crontab
echo "$(( RANDOM % 60 )) * * * * $AV_PATH apply > /var/log/aviary.log 2>&1" >> /etc/crontab

echo Done
